# Generated by Django 3.1.5 on 2021-04-24 19:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210425_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='article',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
